server:
  port: 8080

env: ks-qa1

spring:
  datasource1:
    name: test
    url: jdbc:mysql://59.111.124.162:3306/ga_nsf_config1?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false
    username: qzmysql
    password: MTExYjZkZjQ3ZGFl
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 10
    initialSize: 3
    maxWait: 60000
    minIdle: 3
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  datasource2:
    name: test
    url: jdbc:mysql://59.111.124.162:3306/ga_pf_user_auth?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false
    username: qzmysql
    password: MTExYjZkZjQ3ZGFl
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 10
    initialSize: 3
    maxWait: 60000
    minIdle: 3
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  datasource3:
    name: test
    url: jdbc:mysql://59.111.124.162:3306/ga_nsf_portal1?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false
    username: qzmysql
    password: MTExYjZkZjQ3ZGFl
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 10
    initialSize: 3
    maxWait: 60000
    minIdle: 3
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#mybatis:
#  mapperLocations: classpath:mapper/*.xml,classpath:com/netease/cloud/nsf/db/*.xml
