package com.example.webservice.receive;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-04T14:53:04.236+08:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ReceivePutStateServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ReceivePutStateServiceSoap {

    @WebMethod(operationName = "ReceiveState", action = "http://tempuri.org/ReceiveState")
    @RequestWrapper(localName = "ReceiveState", targetNamespace = "http://tempuri.org/", className = "com.example.webservice.receive.ReceiveState")
    @ResponseWrapper(localName = "ReceiveStateResponse", targetNamespace = "http://tempuri.org/", className = "com.example.webservice.receive.ReceiveStateResponse")
    @WebResult(name = "ReceiveStateResult", targetNamespace = "http://tempuri.org/")
    public String receiveState(

        @WebParam(name = "LaunchPayBillNo", targetNamespace = "http://tempuri.org/")
        String launchPayBillNo,
        @WebParam(name = "ConfirmLaunchDate", targetNamespace = "http://tempuri.org/")
        String confirmLaunchDate,
        @WebParam(name = "LaunchStatus", targetNamespace = "http://tempuri.org/")
        String launchStatus
    );
}
