package com.example.webservice.receive;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-04T14:53:04.229+08:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ReceivePutStateServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ReceivePutStateServiceHttpPost {

    @WebMethod(operationName = "ReceiveState")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public String receiveState(

        @WebParam(partName = "LaunchPayBillNo", name = "LaunchPayBillNo", targetNamespace = "http://tempuri.org/")
        String launchPayBillNo,
        @WebParam(partName = "ConfirmLaunchDate", name = "ConfirmLaunchDate", targetNamespace = "http://tempuri.org/")
        String confirmLaunchDate,
        @WebParam(partName = "LaunchStatus", name = "LaunchStatus", targetNamespace = "http://tempuri.org/")
        String launchStatus
    );
}
