package com.example.webservice.project;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-04T14:52:39.938+08:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ProjectInfoSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ProjectInfoSoap {

    @WebMethod(operationName = "GetProjectName", action = "http://tempuri.org/GetProjectName")
    @RequestWrapper(localName = "GetProjectName", targetNamespace = "http://tempuri.org/", className = "com.example.webservice.project.GetProjectName")
    @ResponseWrapper(localName = "GetProjectNameResponse", targetNamespace = "http://tempuri.org/", className = "com.example.webservice.project.GetProjectNameResponse")
    @WebResult(name = "GetProjectNameResult", targetNamespace = "http://tempuri.org/")
    public String getProjectName(

        @WebParam(name = "ProjectID", targetNamespace = "http://tempuri.org/")
        int projectID
    );

    @WebMethod(operationName = "GetProjectCode", action = "http://tempuri.org/GetProjectCode")
    @RequestWrapper(localName = "GetProjectCode", targetNamespace = "http://tempuri.org/", className = "com.example.webservice.project.GetProjectCode")
    @ResponseWrapper(localName = "GetProjectCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.example.webservice.project.GetProjectCodeResponse")
    @WebResult(name = "GetProjectCodeResult", targetNamespace = "http://tempuri.org/")
    public String getProjectCode(

        @WebParam(name = "ProjectID", targetNamespace = "http://tempuri.org/")
        int projectID
    );
}
