
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.webservice.project;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-04T14:52:39.922+08:00
 * Generated source version: 3.4.2
 */

@WebService(
        serviceName = "ProjectInfo",
        portName = "ProjectInfoSoap12",
        targetNamespace = "http://tempuri.org/",
        wsdlLocation = "classpath:wsdl/ProjectInfo.xml",
        endpointInterface = "com.example.webservice.project.ProjectInfoSoap")

public class ProjectInfoSoap12Impl implements ProjectInfoSoap {

    private static final Logger LOG = Logger.getLogger(ProjectInfoSoap12Impl.class.getName());

    /* (non-Javadoc)
     * @see com.example.webservice.project.ProjectInfoSoap#getProjectName(int projectID)*
     */
    public String getProjectName(int projectID) {
        LOG.info("Executing operation getProjectName");
        System.out.println(projectID);
        try {
            String _return = String.format("projectID:[%s]", projectID);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.example.webservice.project.ProjectInfoSoap#getProjectCode(int projectID)*
     */
    public String getProjectCode(int projectID) {
        LOG.info("Executing operation getProjectCode");
        System.out.println(projectID);
        try {
            String _return = String.format("projectID:[%s]", projectID);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
