
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.webservice.risk;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-04T14:51:34.463+08:00
 * Generated source version: 3.4.2
 *
 */

@WebService(
                      serviceName = "CustomerRiskInfo",
                      portName = "CustomerRiskInfoHttpGet",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "classpath:wsdl/CustomerRiskInfo.xml",
                      endpointInterface = "com.example.webservice.risk.CustomerRiskInfoHttpGet")

public class CustomerRiskInfoHttpGetImpl implements CustomerRiskInfoHttpGet {

    private static final Logger LOG = Logger.getLogger(CustomerRiskInfoHttpGetImpl.class.getName());

    /* (non-Javadoc)
     * @see com.example.webservice.risk.CustomerRiskInfoHttpGet#getCustomerRiskInfo(java.lang.String orgCode, java.lang.String planPutMoney, java.lang.String key)*
     */
    public int getCustomerRiskInfo(String orgCode, String planPutMoney, String key) {
        LOG.info("Executing operation getCustomerRiskInfo");
        System.out.println(orgCode);
        System.out.println(planPutMoney);
        System.out.println(key);
        try {
            int _return = 0;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.example.webservice.risk.CustomerRiskInfoHttpGet#customerLimitIsOut(java.lang.String projectID)*
     */
    public int customerLimitIsOut(String projectID) {
        LOG.info("Executing operation customerLimitIsOut");
        System.out.println(projectID);
        try {
            int _return = 0;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
