package com.example.webservice.risk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-04T14:51:34.475+08:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "CustomerRiskInfoHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomerRiskInfoHttpGet {

    @WebMethod(operationName = "GetCustomerRiskInfo")
    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    public int getCustomerRiskInfo(

        @WebParam(partName = "OrgCode", name = "OrgCode", targetNamespace = "http://tempuri.org/")
        String orgCode,
        @WebParam(partName = "PlanPutMoney", name = "PlanPutMoney", targetNamespace = "http://tempuri.org/")
        String planPutMoney,
        @WebParam(partName = "Key", name = "Key", targetNamespace = "http://tempuri.org/")
        String key
    );

    @WebMethod(operationName = "CustomerLimitIsOut")
    @WebResult(name = "int", targetNamespace = "http://tempuri.org/", partName = "Body")
    public int customerLimitIsOut(

        @WebParam(partName = "ProjectID", name = "ProjectID", targetNamespace = "http://tempuri.org/")
        String projectID
    );
}
