package com.example.webservice.fund;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-04T14:52:00.845+08:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "FundInfoServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface FundInfoServiceSoap {

    /**
     * S1项目合同接口
     *       
     */
    @WebMethod(operationName = "SearchContractsByProjectcode", action = "http://tempuri.org/SearchContractsByProjectcode")
    @RequestWrapper(localName = "SearchContractsByProjectcode", targetNamespace = "http://tempuri.org/", className = "com.example.webservice.fund.SearchContractsByProjectcode")
    @ResponseWrapper(localName = "SearchContractsByProjectcodeResponse", targetNamespace = "http://tempuri.org/", className = "com.example.webservice.fund.SearchContractsByProjectcodeResponse")
    @WebResult(name = "SearchContractsByProjectcodeResult", targetNamespace = "http://tempuri.org/")
    public String searchContractsByProjectcode(

        @WebParam(name = "PROJECT_NUMBER", targetNamespace = "http://tempuri.org/")
        String projectNUMBER,
        @WebParam(name = "MASTER_NO", targetNamespace = "http://tempuri.org/")
        String masterNO
    );

    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "com.example.webservice.fund.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "com.example.webservice.fund.HelloWorldResponse")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    public String helloWorld()
;

    /**
     * S3项目产品信息登记接口
     *       
     */
    @WebMethod(operationName = "FundInfoConfirm", action = "http://tempuri.org/FundInfoConfirm")
    @RequestWrapper(localName = "FundInfoConfirm", targetNamespace = "http://tempuri.org/", className = "com.example.webservice.fund.FundInfoConfirm")
    @ResponseWrapper(localName = "FundInfoConfirmResponse", targetNamespace = "http://tempuri.org/", className = "com.example.webservice.fund.FundInfoConfirmResponse")
    @WebResult(name = "FundInfoConfirmResult", targetNamespace = "http://tempuri.org/")
    public String fundInfoConfirm(

        @WebParam(name = "PROJECT_NUMBER", targetNamespace = "http://tempuri.org/")
        String projectNUMBER,
        @WebParam(name = "FUND_STATUS", targetNamespace = "http://tempuri.org/")
        String fundSTATUS
    );
}
