
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.webservice.fund;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-04T14:52:00.840+08:00
 * Generated source version: 3.4.2
 *
 */

@WebService(
                      serviceName = "FundInfoService",
                      portName = "FundInfoServiceHttpGet",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "classpath:wsdl/FundInfoService.xml",
                      endpointInterface = "com.example.webservice.fund.FundInfoServiceHttpGet")

public class FundInfoServiceHttpGetImpl implements FundInfoServiceHttpGet {

    private static final Logger LOG = Logger.getLogger(FundInfoServiceHttpGetImpl.class.getName());

    /* (non-Javadoc)
     * @see com.example.webservice.fund.FundInfoServiceHttpGet#searchContractsByProjectcode(java.lang.String projectNUMBER, java.lang.String masterNO)*
     */
    public String searchContractsByProjectcode(String projectNUMBER, String masterNO) {
        LOG.info("Executing operation searchContractsByProjectcode");
        System.out.println(projectNUMBER);
        System.out.println(masterNO);
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.example.webservice.fund.FundInfoServiceHttpGet#helloWorld()*
     */
    public String helloWorld() {
        LOG.info("Executing operation helloWorld");
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.example.webservice.fund.FundInfoServiceHttpGet#fundInfoConfirm(java.lang.String projectNUMBER, java.lang.String fundSTATUS)*
     */
    public String fundInfoConfirm(String projectNUMBER, String fundSTATUS) {
        LOG.info("Executing operation fundInfoConfirm");
        System.out.println(projectNUMBER);
        System.out.println(fundSTATUS);
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
