
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.webservice.book;

import javax.jws.WebService;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-05T15:37:10.218+08:00
 * Generated source version: 3.4.2
 */

@WebService(
        serviceName = "BookService",
        portName = "BookServiceSOAP",
        targetNamespace = "http://www.cleverbuilder.com/BookService/",
        wsdlLocation = "classpath:wsdl/BookService.wsdl",
        endpointInterface = "com.example.webservice.book.BookService")

public class BookServiceSOAPImpl implements BookService {

    private static final Logger LOG = Logger.getLogger(BookServiceSOAPImpl.class.getName());

    private Map<String, Book> bookMap = new HashMap<>();

    /* (non-Javadoc)
     * @see com.example.webservice.book.BookService#getBook(com.example.webservice.book.GetBook parameters)*
     */
    public GetBookResponse getBook(GetBook parameters) {
        LOG.info("Executing operation getBook");
        System.out.println(parameters);
        try {
            GetBookResponse _return = new GetBookResponse();
            Book book = bookMap.get(parameters.getID());
            _return.setBook(book);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.example.webservice.book.BookService#addBook(com.example.webservice.book.AddBook parameters)*
     */
    public AddBookResponse addBook(AddBook parameters) {
        LOG.info("Executing operation addBook");
        System.out.println(parameters);
        try {
            AddBookResponse _return = new AddBookResponse();
            for (Book book : parameters.getBook()) {
                bookMap.put(book.getID(), book);
                _return.getBook().add(book);
            }
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.example.webservice.book.BookService#getAllBooks(com.example.webservice.book.GetAllBooks parameters)*
     */
    public GetAllBooksResponse getAllBooks(GetAllBooks parameters) {
        LOG.info("Executing operation getAllBooks");
        System.out.println(parameters);
        try {
            GetAllBooksResponse _return = new GetAllBooksResponse();
            _return.getBook().addAll(bookMap.values());
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
