
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.webservice.message;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-04T14:52:21.593+08:00
 * Generated source version: 3.4.2
 *
 */

@WebService(
                      serviceName = "MessageService",
                      portName = "MessageServiceSoap12",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "classpath:wsdl/MessageService.xml",
                      endpointInterface = "com.example.webservice.message.MessageServiceSoap")

public class MessageServiceSoap12Impl implements MessageServiceSoap {

    private static final Logger LOG = Logger.getLogger(MessageServiceSoap12Impl.class.getName());


    /* (non-Javadoc)
     * @see com.example.webservice.message.MessageServiceSoap#queryMessage(java.lang.String inputXml)*
     */
    public String queryMessage(String inputXml) {
        LOG.info("Executing operation queryMessage");
        System.out.println(inputXml);
        try {
            String _return = String.format("inputXml:[%s]", inputXml);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
