package com.example.webservice.message;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-04T14:52:21.612+08:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "MessageServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface MessageServiceSoap {

    @WebMethod(operationName = "QueryMessage", action = "http://tempuri.org/QueryMessage")
    @RequestWrapper(localName = "QueryMessage", targetNamespace = "http://tempuri.org/", className = "com.example.webservice.message.QueryMessage")
    @ResponseWrapper(localName = "QueryMessageResponse", targetNamespace = "http://tempuri.org/", className = "com.example.webservice.message.QueryMessageResponse")
    @WebResult(name = "QueryMessageResult", targetNamespace = "http://tempuri.org/")
    public String queryMessage(

        @WebParam(name = "inputXml", targetNamespace = "http://tempuri.org/")
        String inputXml
    );
}
